const quizData = [
  {
    question: "Which language runs in a web browser?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
  },
  {
    question: "What does CSS stand for?",
    a: "Central Style Sheets",
    b: "Cascading Style Sheets",
    c: "Cascading Simple Sheets",
    d: "Cars SUVs Sailboats",
    correct: "b",
  },
  {
    question: "What does HTML stand for?",
    a: "Hypertext Markup Language",
    b: "Hypertext Markdown Language",
    c: "Hyperloop Machine Language",
    d: "Helicopters Terminals Motorboats Lamborginis",
    correct: "a",
  },
  {
    question: "What year was JavaScript launched?",
    a: "1996",
    b: "1995",
    c: "1994",
    d: "none of the above",
    correct: "b",
  },
  {
    question: "Which HTML tag is used to define an internal style sheet?",
    a: "<css>",
    b: "<script>",
    c: "<style>",
    d: "<link>",
    correct: "c",
  },
  {
    question: "Which property is used to change text color in CSS?",
    a: "font-color",
    b: "text-color",
    c: "color",
    d: "background-color",
    correct: "c",
  },
  {
    question: "Inside which HTML element do we put JavaScript?",
    a: "<js>",
    b: "<javascript>",
    c: "<script>",
    d: "<code>",
    correct: "c",
  },
  {
    question: "Which symbol is used for comments in JavaScript?",
    a: "<!-- -->",
    b: "#",
    c: "//",
    d: "**",
    correct: "c",
  },
  {
    question: "Which HTML attribute is used to define inline styles?",
    a: "font",
    b: "class",
    c: "styles",
    d: "style",
    correct: "d",
  },
  {
    question: "How do you write 'Hello World' in an alert box?",
    a: "alertBox('Hello World');",
    b: "msg('Hello World');",
    c: "alert('Hello World');",
    d: "console.log('Hello World');",
    correct: "c",
  },
  {
    question: "Which CSS property controls the text size?",
    a: "font-style",
    b: "text-size",
    c: "font-size",
    d: "text-style",
    correct: "c",
  },
  {
    question: "Which HTML tag is used to create a hyperlink?",
    a: "<link>",
    b: "<a>",
    c: "<href>",
    d: "<url>",
    correct: "b",
  },
  {
    question: "Which keyword is used to declare a variable in JavaScript?",
    a: "var",
    b: "int",
    c: "string",
    d: "boolean",
    correct: "a",
  },
  {
    question: "Which CSS property is used to change the background color?",
    a: "color",
    b: "bgcolor",
    c: "background-color",
    d: "background",
    correct: "c",
  },
  {
    question: "Which HTML tag is used for the largest heading?",
    a: "<h6>",
    b: "<heading>",
    c: "<h1>",
    d: "<head>",
    correct: "c",
  },
  {
    question: "Which operator is used to assign a value in JavaScript?",
    a: "==",
    b: "===",
    c: "=",
    d: "=>",
    correct: "c",
  },
  {
    question: "Which CSS unit is relative to the parent element?",
    a: "px",
    b: "em",
    c: "cm",
    d: "mm",
    correct: "b",
  },
  {
    question: "How do you write an IF statement in JavaScript?",
    a: "if i == 5 then",
    b: "if (i == 5)",
    c: "if i = 5",
    d: "if i equals 5",
    correct: "b",
  },
  {
    question: "Which HTML tag is used to display an image?",
    a: "<image>",
    b: "<img>",
    c: "<src>",
    d: "<picture>",
    correct: "b",
  },
  {
    question: "Which CSS property is used to make text bold?",
    a: "font-weight",
    b: "font-bold",
    c: "text-weight",
    d: "bold",
    correct: "a",
  },
  {
    question: "Which method is used to print something in the browser console?",
    a: "print()",
    b: "log()",
    c: "console.print()",
    d: "console.log()",
    correct: "d",
  },
  {
    question: "Which HTML element is used for unordered lists?",
    a: "<ol>",
    b: "<ul>",
    c: "<li>",
    d: "<list>",
    correct: "b",
  },
  {
    question: "Which CSS property adds space inside an element?",
    a: "margin",
    b: "border",
    c: "padding",
    d: "spacing",
    correct: "c",
  },
  {
    question: "Which JavaScript function converts a string to an integer?",
    a: "Number()",
    b: "parseInt()",
    c: "parseFloat()",
    d: "String()",
    correct: "b",
  },
  {
    question: "Which HTML tag is used to create a button?",
    a: "<input>",
    b: "<btn>",
    c: "<button>",
    d: "<click>",
    correct: "c",
  },
  {
    question: "Which CSS property controls element alignment using flexbox?",
    a: "align-items",
    b: "position",
    c: "float",
    d: "display",
    correct: "a",
  },
  {
    question: "Which JavaScript keyword stops a loop?",
    a: "stop",
    b: "exit",
    c: "break",
    d: "return",
    correct: "c",
  },
  {
    question: "Which HTML tag defines a table row?",
    a: "<td>",
    b: "<th>",
    c: "<tr>",
    d: "<table>",
    correct: "c",
  },
  {
    question: "Which CSS property changes the cursor on hover?",
    a: "mouse",
    b: "cursor",
    c: "pointer",
    d: "hover",
    correct: "b",
  },
  {
    question: "Which JavaScript data type is NOT primitive?",
    a: "String",
    b: "Number",
    c: "Boolean",
    d: "Object",
    correct: "d",
  },
  {
    question: "Which HTML tag is used to define a form?",
    a: "<input>",
    b: "<form>",
    c: "<field>",
    d: "<submit>",
    correct: "b",
  },
  {
    question: "Which CSS property is used to hide an element?",
    a: "opacity: 0",
    b: "display: none",
    c: "visibility: hidden",
    d: "all of the above",
    correct: "d",
  },
  {
    question: "Which JavaScript method removes the last element of an array?",
    a: "pop()",
    b: "push()",
    c: "shift()",
    d: "slice()",
    correct: "a",
  },
  {
    question: "Which HTML attribute is required for images?",
    a: "title",
    b: "alt",
    c: "src",
    d: "href",
    correct: "c",
  },
  {
    question: "Which CSS property adds shadow to text?",
    a: "box-shadow",
    b: "text-shadow",
    c: "font-shadow",
    d: "shadow",
    correct: "b",
  },
  {
    question: "Which JavaScript keyword declares a block-scoped variable?",
    a: "var",
    b: "let",
    c: "const",
    d: "both b and c",
    correct: "d",
  },
  {
    question: "Which HTML tag is semantic?",
    a: "<div>",
    b: "<span>",
    c: "<section>",
    d: "<b>",
    correct: "c",
  },
  {
    question: "Which CSS layout model is one-dimensional?",
    a: "Grid",
    b: "Flexbox",
    c: "Float",
    d: "Position",
    correct: "b",
  },
  {
    question: "Which JavaScript method joins array elements into a string?",
    a: "concat()",
    b: "join()",
    c: "merge()",
    d: "combine()",
    correct: "b",
  },
  {
    question: "Which HTML tag defines navigation links?",
    a: "<nav>",
    b: "<menu>",
    c: "<header>",
    d: "<links>",
    correct: "a",
  },
  {
    question: "Which CSS property rounds the corners of an element?",
    a: "border-style",
    b: "corner-radius",
    c: "border-radius",
    d: "radius",
    correct: "c",
  },
  {
    question: "Which JavaScript method checks array length?",
    a: "size",
    b: "count",
    c: "length",
    d: "items",
    correct: "c",
  },
  {
    question: "Which HTML tag is used to play video?",
    a: "<media>",
    b: "<movie>",
    c: "<video>",
    d: "<play>",
    correct: "c",
  },
  {
    question: "Which CSS property sets the font?",
    a: "font-family",
    b: "text-font",
    c: "font-style",
    d: "font-type",
    correct: "a",
  },
  {
    question: "Which JavaScript function runs repeatedly at intervals?",
    a: "setTimeout",
    b: "setInterval",
    c: "repeat",
    d: "loop",
    correct: "b",
  }
];

export default quizData